// Reusable PDF generation helpers built on pdf-lib.
// LTR + Latin-only (StandardFonts don't support Unicode). Use "BDT" instead of "৳".
import { PDFDocument, PDFFont, PDFPage, StandardFonts, rgb } from "pdf-lib";

export const PAGE_W = 595.28;
export const PAGE_H = 841.89;
export const MARGIN = 50;
const CONTENT_W = PAGE_W - MARGIN * 2;
const EMERALD = rgb(16 / 255, 185 / 255, 129 / 255);
const SLATE = rgb(71 / 255, 85 / 255, 105 / 255);
const MUTED = rgb(100 / 255, 116 / 255, 139 / 255);
const BORDER = rgb(203 / 255, 213 / 255, 225 / 255);
const ROW_ALT = rgb(247 / 255, 251 / 255, 249 / 255);
const KPI_BG = rgb(245 / 255, 252 / 255, 249 / 255);
const KPI_BORDER = rgb(167 / 255, 243 / 255, 208 / 255);
const WHITE = rgb(1, 1, 1);
type Ctx = { doc: PDFDocument; font: PDFFont; bold: PDFFont };
export type PdfCtx = Ctx & { page: PDFPage; y: number };

function newPage(ctx: PdfCtx): { page: PDFPage; y: number } {
  const page = ctx.doc.addPage([PAGE_W, PAGE_H]);
  ctx.page = page;
  return { page, y: PAGE_H - MARGIN };
}

export async function createPdfDoc(title: string, tenantName: string): Promise<PdfCtx> {
  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  doc.setTitle(title);
  doc.setAuthor(tenantName);
  doc.setCreator("Madrasa Manager ERP");
  doc.setProducer("Madrasa Manager ERP (pdf-lib)");
  const page = doc.addPage([PAGE_W, PAGE_H]);
  page.drawRectangle({ x: 0, y: PAGE_H - 6, width: PAGE_W, height: 6, color: EMERALD });
  let y = PAGE_H - MARGIN;
  page.drawText(tenantName, { x: MARGIN, y: y - 14, size: 18, font: bold, color: SLATE });
  y -= 26;
  const titleW = bold.widthOfTextAtSize(title, 12) + 18;
  page.drawRectangle({
    x: MARGIN, y: y - 16, width: titleW, height: 20,
    color: EMERALD, borderColor: EMERALD, borderWidth: 0,
  });
  page.drawText(title, { x: MARGIN + 9, y: y - 12, size: 12, font: bold, color: WHITE });
  y -= 28;
  const dateStr = new Date().toLocaleString("en-GB", {
    day: "2-digit", month: "short", year: "numeric",
    hour: "2-digit", minute: "2-digit",
  });
  page.drawText(`Generated: ${dateStr}`, { x: MARGIN, y, size: 9, font, color: MUTED });
  page.drawText("Generated by Madrasa Manager ERP", {
    x: PAGE_W - MARGIN - font.widthOfTextAtSize("Generated by Madrasa Manager ERP", 9),
    y, size: 9, font, color: MUTED,
  });
  y -= 14;
  page.drawLine({
    start: { x: MARGIN, y }, end: { x: PAGE_W - MARGIN, y },
    thickness: 1, color: BORDER,
  });
  y -= 22;
  return { doc, font, bold, page, y };
}

export function addSection(ctx: PdfCtx, title: string): number {
  let { y, page, font, bold } = ctx;
  if (y < MARGIN + 60) ({ page, y } = newPage(ctx));
  page.drawRectangle({ x: MARGIN, y: y - 11, width: 3.5, height: 14, color: EMERALD });
  page.drawText(title, { x: MARGIN + 10, y: y - 8, size: 12.5, font: bold, color: SLATE });
  return y - 24;
}

export function addParagraph(ctx: PdfCtx, text: string): number {
  let { y, page, font } = ctx;
  const size = 10, lh = 14, maxW = CONTENT_W;
  const words = text.split(" ");
  let line = "";
  const emit = (s: string) => {
    if (y < MARGIN + lh) ({ page, y } = newPage(ctx));
    page.drawText(s, { x: MARGIN, y, size, font, color: SLATE });
    y -= lh;
  };
  for (const w of words) {
    const test = line ? `${line} ${w}` : w;
    if (font.widthOfTextAtSize(test, size) > maxW) { emit(line); line = w; }
    else line = test;
  }
  if (line) emit(line);
  ctx.y = y;
  return y - 4;
}

export function addKpiRow(ctx: PdfCtx, kpis: { label: string; value: string }[]): number {
  let { y, page, font, bold } = ctx;
  if (kpis.length === 0) return y;
  const n = kpis.length, gap = 10;
  const cardW = (CONTENT_W - gap * (n - 1)) / n, cardH = 44;
  if (y < MARGIN + cardH + 4) ({ page, y } = newPage(ctx));
  let x = MARGIN;
  for (const kpi of kpis) {
    page.drawRectangle({
      x, y: y - cardH, width: cardW, height: cardH,
      color: KPI_BG, borderColor: KPI_BORDER, borderWidth: 1,
    });
    page.drawRectangle({ x, y: y - cardH, width: 3, height: cardH, color: EMERALD });
    page.drawText(kpi.label, { x: x + 10, y: y - 14, size: 8, font, color: MUTED });
    let valText = kpi.value, valSize = 14;
    while (bold.widthOfTextAtSize(valText, valSize) > cardW - 20 && valSize > 9) valSize -= 0.5;
    page.drawText(valText, { x: x + 10, y: y - 32, size: valSize, font: bold, color: SLATE });
    x += cardW + gap;
  }
  ctx.y = y - cardH - 8;
  return ctx.y;
}

export function addTable(
  ctx: PdfCtx, headers: string[], rows: string[][], colWidths: number[],
): number {
  let { y, page, font, bold } = ctx;
  const rowH = 20, headerH = 22;
  const totalW = colWidths.reduce((a, b) => a + b, 0);
  if (totalW > CONTENT_W) {
    const scale = CONTENT_W / totalW;
    for (let i = 0; i < colWidths.length; i++) colWidths[i] *= scale;
  }
  const drawHeader = () => {
    if (y < MARGIN + headerH + rowH) ({ page, y } = newPage(ctx));
    let x = MARGIN;
    page.drawRectangle({ x, y: y - headerH, width: totalW, height: headerH, color: EMERALD });
    for (let i = 0; i < headers.length; i++) {
      const txt = truncate(headers[i], colWidths[i] - 8, bold, 9.5);
      page.drawText(txt, { x: x + 4, y: y - 14, size: 9.5, font: bold, color: WHITE });
      x += colWidths[i];
    }
    y -= headerH;
  };
  drawHeader();
  for (let r = 0; r < rows.length; r++) {
    if (y < MARGIN + rowH) {
      page.drawLine({
        start: { x: MARGIN, y }, end: { x: MARGIN + totalW, y },
        thickness: 0.5, color: BORDER,
      });
      ({ page, y } = newPage(ctx));
      drawHeader();
    }
    let x = MARGIN;
    page.drawRectangle({ x, y: y - rowH, width: totalW, height: rowH, color: ROW_ALT });
    if (r % 2 !== 0) {
      page.drawRectangle({ x, y: y - rowH, width: totalW, height: rowH, color: WHITE });
    }
    for (let c = 0; c < rows[r].length; c++) {
      const txt = truncate(rows[r][c] ?? "", colWidths[c] - 8, font, 9);
      page.drawText(txt, { x: x + 4, y: y - 13, size: 9, font, color: SLATE });
      x += colWidths[c];
    }
    y -= rowH;
  }
  const top = y + rows.length * rowH + headerH;
  page.drawRectangle({
    x: MARGIN, y, width: totalW, height: top - y,
    color: undefined, borderColor: BORDER, borderWidth: 0.5,
  });
  ctx.y = y - 8;
  return ctx.y;
}

function truncate(s: string, maxW: number, font: PDFFont, size: number): string {
  if (font.widthOfTextAtSize(s, size) <= maxW) return s;
  let lo = 0, hi = s.length;
  while (lo < hi) {
    const mid = Math.floor((lo + hi + 1) / 2);
    if (font.widthOfTextAtSize(s.slice(0, mid) + "…", size) <= maxW) lo = mid;
    else hi = mid - 1;
  }
  return lo > 0 ? s.slice(0, lo) + "…" : "";
}

export function addFooter(ctx: PdfCtx, pageNum: number): void {
  const { page, font } = ctx;
  const total = ctx.doc.getPageCount();
  page.drawLine({
    start: { x: MARGIN, y: MARGIN - 14 }, end: { x: PAGE_W - MARGIN, y: MARGIN - 14 },
    thickness: 0.5, color: BORDER,
  });
  page.drawText("Madrasa Manager ERP", { x: MARGIN, y: MARGIN - 26, size: 8, font, color: MUTED });
  const txt = `Page ${pageNum} of ${total}`;
  page.drawText(txt, {
    x: PAGE_W - MARGIN - font.widthOfTextAtSize(txt, 8), y: MARGIN - 26,
    size: 8, font, color: MUTED,
  });
}

export async function finalizePdf(ctx: PdfCtx): Promise<Uint8Array> {
  // Add footers to all pages at the end (now that total count is known)
  const pages = ctx.doc.getPages();
  pages.forEach((p, i) => {
    addFooter({ ...ctx, page: p, y: 0 }, i + 1);
  });
  return ctx.doc.save();
}

export const PDF_BRAND = { EMERALD, SLATE, MUTED, BORDER };
