"use client";
// AiInsights — auto-generated insight cards + AI context data snapshot.
import * as React from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  CheckCircle2, AlertTriangle, Info, RefreshCw, Sparkles,
  Users, Wallet, BookOpen, CalendarCheck,
} from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Skeleton } from "@/components/ui/skeleton";
import { useApp } from "@/store/app-store";
import { toast } from "sonner";
import type { AiContextSnapshot } from "./ai-view";

type InsightType = "positive" | "warning" | "info";
type Insight = { type: InsightType; title: string; description: string; action?: string };

const INSIGHT_STYLE: Record<InsightType, { icon: typeof Info; ring: string; bg: string; text: string }> = {
  positive: { icon: CheckCircle2, ring: "ring-emerald-200 dark:ring-emerald-900/50", bg: "bg-emerald-500", text: "text-emerald-700 dark:text-emerald-300" },
  warning: { icon: AlertTriangle, ring: "ring-amber-200 dark:ring-amber-900/50", bg: "bg-amber-500", text: "text-amber-700 dark:text-amber-300" },
  info: { icon: Info, ring: "ring-sky-200 dark:ring-sky-900/50", bg: "bg-sky-500", text: "text-sky-700 dark:text-sky-300" },
};

export function AiInsights({ context }: { context: AiContextSnapshot | null }) {
  const { t, locale, dir } = useApp();
  const [insights, setInsights] = React.useState<Insight[]>([]);
  const [loading, setLoading] = React.useState(false);
  const [firstLoaded, setFirstLoaded] = React.useState(false);

  const cur = (n: number) =>
    new Intl.NumberFormat(locale === "ar" ? "ar-EG" : locale === "bn" ? "bn-BD" : "en-US", {
      maximumFractionDigits: 0,
    }).format(n || 0);

  const loadInsights = React.useCallback(async () => {
    setLoading(true);
    try {
      const res = await fetch("/api/ai/insights", { cache: "no-store" });
      const json = await res.json();
      if (!json?.ok) throw new Error(json?.error || t("ai.error"));
      setInsights(json.data.insights as Insight[]);
    } catch (e) {
      toast.error(e instanceof Error ? e.message : t("ai.error"));
    } finally {
      setLoading(false);
      setFirstLoaded(true);
    }
  }, [t]);

  React.useEffect(() => {
    loadInsights();
  }, [loadInsights]);

  const ctxStats = context
    ? [
        { label: t("ai.studentsCount"), value: cur(context.students), icon: Users, tone: "from-emerald-500 to-teal-600" },
        { label: t("ai.fundsBalance"), value: `৳${cur(context.funds)}`, icon: Wallet, tone: "from-amber-500 to-orange-600" },
        { label: t("ai.hifzRate"), value: cur(context.hifzRate), icon: BookOpen, tone: "from-violet-500 to-purple-600" },
        { label: t("ai.attendanceRate"), value: `${context.attendanceRate}%`, icon: CalendarCheck, tone: "from-sky-500 to-cyan-600" },
      ]
    : [];

  return (
    <div className="space-y-4" dir={dir()}>
      {/* Insights panel */}
      <Card className="border-violet-200/60 dark:border-violet-900/40">
        <CardHeader className="flex flex-row items-center justify-between gap-2 pb-3">
          <div className="flex items-center gap-2">
            <div className="grid size-8 place-items-center rounded-lg bg-gradient-to-br from-violet-500 to-purple-600 text-white">
              <Sparkles className="size-4" />
            </div>
            <div>
              <CardTitle className="text-sm">{t("ai.insights")}</CardTitle>
              <p className="text-[10px] text-muted-foreground">Auto-generated by Mufakkir</p>
            </div>
          </div>
          <Button
            size="sm"
            variant="outline"
            onClick={loadInsights}
            disabled={loading}
            className="h-7 gap-1.5 border-violet-200 text-violet-700 hover:bg-violet-50 dark:border-violet-900/50 dark:text-violet-300 dark:hover:bg-violet-950/40 text-xs"
          >
            <RefreshCw className={`size-3 ${loading ? "animate-spin" : ""}`} />
            {t("ai.refreshInsights")}
          </Button>
        </CardHeader>
        <CardContent className="pt-0">
          <ScrollArea className="h-[280px] pe-2">
            {loading && !firstLoaded ? (
              <div className="space-y-2">
                {[0, 1, 2].map((i) => (
                  <Skeleton key={i} className="h-20 w-full rounded-xl" />
                ))}
              </div>
            ) : insights.length === 0 ? (
              <div className="flex flex-col items-center justify-center py-8 text-center">
                <Info className="size-7 text-muted-foreground/60 mb-2" />
                <p className="text-xs font-medium">{t("ai.emptyInsights")}</p>
                <p className="mt-1 text-[10px] text-muted-foreground max-w-[200px]">{t("ai.emptyInsightsDesc")}</p>
              </div>
            ) : (
              <div className="space-y-2.5">
                <AnimatePresence initial={false}>
                  {insights.map((ins, idx) => {
                    const style = INSIGHT_STYLE[ins.type] || INSIGHT_STYLE.info;
                    const Icon = style.icon;
                    return (
                      <motion.div
                        key={`${ins.title}-${idx}`}
                        initial={{ opacity: 0, y: 6 }}
                        animate={{ opacity: 1, y: 0 }}
                        exit={{ opacity: 0 }}
                        transition={{ duration: 0.2, delay: idx * 0.04 }}
                        className={`rounded-xl border bg-card p-3 ring-1 ${style.ring}`}
                      >
                        <div className="flex items-start gap-2.5">
                          <div className={`grid size-7 shrink-0 place-items-center rounded-lg ${style.bg} text-white`}>
                            <Icon className="size-3.5" />
                          </div>
                          <div className="min-w-0 flex-1">
                            <p className="text-xs font-semibold leading-tight" dir="auto">{ins.title}</p>
                            <p className="mt-1 text-[11px] leading-relaxed text-muted-foreground" dir="auto">{ins.description}</p>
                            {ins.action && (
                              <div className={`mt-1.5 flex items-start gap-1 text-[11px] font-medium ${style.text}`} dir="auto">
                                <span className="shrink-0">→</span>
                                <span>{ins.action}</span>
                              </div>
                            )}
                          </div>
                        </div>
                      </motion.div>
                    );
                  })}
                </AnimatePresence>
              </div>
            )}
          </ScrollArea>
        </CardContent>
      </Card>

      {/* Context data snapshot */}
      <Card className="border-violet-200/60 dark:border-violet-900/40 bg-gradient-to-br from-violet-50/50 to-purple-50/50 dark:from-violet-950/20 dark:to-purple-950/20">
        <CardHeader className="pb-3">
          <div className="flex items-center gap-2">
            <div className="grid size-7 place-items-center rounded-lg bg-violet-200/60 dark:bg-violet-900/40 text-violet-700 dark:text-violet-300">
              <Info className="size-3.5" />
            </div>
            <CardTitle className="text-sm">{t("ai.contextData")}</CardTitle>
          </div>
        </CardHeader>
        <CardContent>
          {!context ? (
            <div className="grid grid-cols-2 gap-2">
              {[0, 1, 2, 3].map((i) => <Skeleton key={i} className="h-14 rounded-xl" />)}
            </div>
          ) : (
            <div className="grid grid-cols-2 gap-2">
              {ctxStats.map((s) => {
                const Icon = s.icon;
                return (
                  <div
                    key={s.label}
                    className="rounded-xl bg-background/70 dark:bg-background/40 p-2.5 backdrop-blur-sm border border-violet-100 dark:border-violet-900/30"
                  >
                    <div className="flex items-center gap-2">
                      <div className={`grid size-6 shrink-0 place-items-center rounded-md bg-gradient-to-br ${s.tone} text-white`}>
                        <Icon className="size-3" />
                      </div>
                      <p className="text-[10px] text-muted-foreground truncate">{s.label}</p>
                    </div>
                    <p className="mt-1 text-base font-bold tabular-nums" dir="auto">{s.value}</p>
                  </div>
                );
              })}
            </div>
          )}
          {context && (
            <p className="mt-3 text-[10px] text-muted-foreground leading-relaxed">
              <span className="font-medium text-violet-700 dark:text-violet-300">{t("ai.contextUsed")}:</span>{" "}
              {t("ai.welcome").slice(0, 60)}...
            </p>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
